# Generated by Django 5.0.8 on 2024-08-16 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='library',
            old_name='book',
            new_name='books',
        ),
    ]
